# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.loader.txt:
        class: AppBundle\Game\Loader\TextFileLoader
        tags:
            - { type: txt, name: word_list.loader }
    app.loader.xml:
        class: AppBundle\Game\Loader\XmlFileLoader
        tags:
            - { type: xml, name: word_list.loader }
    app.wordlist:
        class: AppBundle\Game\WordList
        calls:
            - { method: loadDictionaries, arguments: [ "%dictionaries%" ] }
    app.game_context:
        class: AppBundle\Game\GameContext
        arguments: [ "@session" ]
    app.game_runner:
        class: AppBundle\Game\GameRunner
        arguments: [ "@app.game_context", "@app.wordlist" ]
    game_runner:
        alias: app.game_runner

    app.manager.user:
        class: AppBundle\Manager\UserManager
        arguments: ["@doctrine.orm.entity_manager", "@security.password_encoder"]

    app.security.voter.game:
        class: AppBundle\Security\GameVoter
        public: false
        tags:
            - { name: security.voter }

    app.event_subscriber.open_close:
        class: AppBundle\EventSubscriber\OpenCloseSubscriber
        arguments:
            - "@templating"
        tags:
            - { name: kernel.event_subscriber }

